### ISSUE TITLE
Support for "Update - 14 November 2023"

### ISSUE THREAD

**Issue by myl7** [myl7/remark-github-beta-blockquote-admonitions#11]
See the update "Update - 14 November 2023" in [the original discussion]

[the original discussion]: https://github.com/orgs/community/discussions/16925

**Comment by JulianCataldo** [comment]
Hello,

with the GH provided example:

```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]  
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]  
> Negative potential consequences of an action.
```

The **two spaces** for carriage returns, after the `]` are not taken into account. Removing them fixes this.

Also TIP and CAUTION are not picked up. But I guess that's part of why you opened this issue ;)

Bye, and thank you for making this!

**Comment by myl7** [comment]
Supported in [v3.1.0] and [v2.2.0]

[v3.1.0]: https://github.com/myl7/remark-github-beta-blockquote-admonitions/releases/tag/v3.1.0
[v2.2.0]: https://github.com/myl7/remark-github-beta-blockquote-admonitions/releases/tag/v2.2.0
