### ISSUE TITLE
New syntax

### ISSUE THREAD

**Issue by Ayc0** [myl7/remark-github-beta-blockquote-admonitions#3]
GitHub decided to test another syntax (see https://github.com/orgs/community/discussions/16925)

```md
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.
```

**Comment by myl7** [comment]
Thanks for the information!
The new syntax will be supported asap (within this week I think).
Meanwhile the old syntax will be preserved with an option to enable.

**Comment by myl7** [comment]
The new syntax has been supported in v2.
Migration help has been added to README.

**Comment by Ayc0** [comment]
So fast!
Thanks 🙏
