### ISSUE TITLE
Issues with `ul` and `ol` as the content

### ISSUE THREAD

**Issue by p3yman** [myl7/remark-github-beta-blockquote-admonitions#4]
Hey, thanks for the amazing package.

I have an issue with using it, it works with normal text, images, and links but not lists like `ul` and `ol`. Can I fix it using configs or something that needs to be added to the package?

```markdown
> [!NOTE]
> - Here you go

> [!NOTE]
>  1. Here you go
```

**Comment by myl7** [comment]
Fixed in v2.1.1

Thanks for the catch!

**Comment by p3yman** [comment]
Awesome! Thanks for such a quick response.
