### ISSUE TITLE
How to use with MDXRemote ?

### ISSUE THREAD

**Issue by akarabach** [myl7/remark-github-beta-blockquote-admonitions#9]
Is there any way to use with MDXRemote ?

```typescript
import plugin from 'remark-github-beta-blockquote-admonitions';

 <MDXRemote
  source={post.fullStory ?? ''}
  options={{
    mdxOptions: {
      remarkPlugins: [remarkGfm, plugin],
      rehypePlugins: [],
    },
  }}
/>
```

**Comment by myl7** [comment]
v2 should work fine with `MDXRemote` of `next-mdx-remote`

See https://github.com/myl7/remark-github-beta-blockquote-admonitions#compatibility

**Comment by akarabach** [comment]
do you have an example how this should be configured ? I'm using v2, but the config above is not working

**Comment by myl7** [comment]
See https://github.com/myl7/remark-github-beta-blockquote-admonitions-next-mdx-remote-example

It is based on the app router. For the page router the code should be similar, just requires normal migration between the two routers. Tell me if you also need an example for that.

**Comment by akarabach** [comment]
thanks for example, I will close this one
